In [6]:
def length_covert():
  print('Convert Length: 1 for m to ft\n 2 for ft to m')
  choice = int(input('Enter your choice: '))
  if choice == 1:
    value = float(input('Enter value in m: '))
    result = value * 3.2
    print(f'{value} m = {result} ft')
  elif choice == 2:
    value = float(input('Enter value in ft: '))
    result = value/3.2
    print(f'{value} ft = {result} m')
  else:
    raise Exception('Invalid choice')

def weight_convert():
  print('Convert Weight: 1 for kg to lb\n 2 for lb to kg')
  choice = int(input('Enter your choice: '))
  if(choice == 1):
    value = float(input('Enter value in kg: '))
    result = value * 2.2
    print(f'{value} kg = {result} lb')
  elif choice ==2:
    value = float(input('Enter value in lb: '))
    result = value/2.2
    print(f'{value} lb = {result} kg')
  else:
    raise Exception('Invalid choice')

def volume_convert():
  print('Convert Volume: 1 for l to gallons\n 2 for gallons to liters')
  choice = int(input('Enter your choice'))
  if choice==1:
    value = float(input('Enter value in l: '))
    result = value * 0.2
    print(f'{value} l = {result} gallons')
  elif choice == 2:
    value = float(input('Enter value in gallons: '))
    result = value/0.2
    print(f'{value} gallons = {result} l')
  else:
    raise Exception('Invalid choice')

def main():
  print('Convert Program')
  print('1. Length\n2. Weight\n3. Volume')
  choice = int(input('Enter your choice: '))
  if choice == 1:
    length_covert()
  elif choice == 2:
    weight_convert()
  elif choice ==3 :
    volume_convert()
  else:
    raise Exception('Invalid choice')
main()

Convert Program
1. Length
2. Weight
3. Volume
Enter your choice: 2
Convert Weight: 1 for kg to lb
 2 for lb to kg
Enter your choice: 1
Enter value in kg: 22
22.0 kg = 48.400000000000006 lb


In [7]:
# Question 2
def find_sum(numbers):
  sum = 0
  for num in numbers:
    sum += num
  return sum

def avg(num):
  total = find_sum(num)
  avg = total/len(num)
  return avg

def maximum(num):
  max_value = max(num)
  return max_value

def minimum(num):
  min_value = min(num)
  return min_value

def main():
  print('Enter your choice: 1 for sum\n2 for average\n3 for maximum\n4 for minimum')
  try:
    choice = int(input('Enter your choice: '))
    nums = input('Enter numbers seperate by spaces: ')
    if nums.strip() == "":
      raise Exception('Invalid input')
    number = []
    split_nums = nums.split()
    if len(split_nums) == 0:
      raise Exception('Invalid input')

    for num in split_nums:
      number.append(int(num))

    if choice == 1:
      print("Sum:", find_sum(number))

    elif choice == 2:
      print("Average:", avg(number))

    elif choice == 3:
      print("Maximum:", maximum(number))

    elif choice == 4:
      print("Minimum:", minimum(number))

    else:
      raise ValueError("Invalid choice")

  except ValueError:
    print('Invalid input')
main()

Enter your choice: 1 for sum
2 for average
3 for maximum
4 for minimum
Enter your choice: 2
Enter numbers seperate by spaces: 13 7 15
Average: 11.666666666666666


In [8]:
# Question 3
def extract_every_other(lst):
  new_nums = []
  for nums in range(len(lst)):
    if(nums %2 ==0):
      new_nums.append(lst[nums])
  return new_nums

input = [1,2,3,4,5]
print(extract_every_other(input))

[1, 3, 5]


In [9]:
# Question 4
def get_sublist(lst, start, end):
    """
    Returns a sublist from the given list starting from index 'start'
    and ending at index 'end' (inclusive).

    Parameters:
    lst (list): The original list
    start (int): Starting index
    end (int): Ending index

    Returns:
    list: The extracted sublist
    """

    sublist = []

    for i in range(start, end + 1):
        sublist.append(lst[i])

    return sublist

numbers = [1, 2, 3, 4, 5, 6]
result = get_sublist(numbers, 2, 4)

print(result)

[3, 4, 5]


In [10]:
def reverse(lst):
  reveresed = lst[::-1]
  return reveresed

number = [1,2,3,4,5]
print(reverse(number))

[5, 4, 3, 2, 1]


In [11]:
def remove_first_last(lst):
  return lst[1:-1]

numbers = [1,2,3,4,5]
print(remove_first_last(numbers))

[2, 3, 4]


In [12]:
def get_first_n(lst, n):
  return lst[:n]

numbers = [1,2,3,4,5]
print(get_first_n(numbers,4))


[1, 2, 3, 4]


In [13]:
def get_last_n(lst, n):
  return lst[-n:]

numbers=[1,2,3,4,5]
print(get_last_n(numbers,3))

[3, 4, 5]


In [14]:
def reverse_skip(lst):
  return lst[::-2]

numbers = [1,2,3,4,5]
print(reverse_skip(numbers))

[5, 3, 1]


In [15]:
def flatten(lst):
  flat_list=[]

  for sublist in lst:
    for item in sublist:
      flat_list.append(item)
  return flat_list

nested = [[1, 2], [3, 4], [5]]
result = flatten(nested)

print(result)

[1, 2, 3, 4, 5]


In [16]:
def access_nested_element(lst, indices):
    element = lst

    for index in indices:
        element = element[index]

    return element

lst = [[1,2,3], [4,5,6], [7,8,9]]
indices = [1,2]

result = access_nested_element(lst, indices)
print(result)

6


In [17]:
def remove_element(lst, elem):
    result = []

    for item in lst:
        if isinstance(item, list):
            result.append(remove_element(item, elem))
        else:
            if item != elem:
                result.append(item)

    return result

lst = [[1, 2], [3, 2], [4, 5]]
elem = 2

result = remove_element(lst, elem)
print(result)

[[1], [3], [4, 5]]


In [18]:
def sum_nested(lst):
  total_sum = 0
  for element in lst:
    if isinstance(element, list):
      total_sum += sum_nested(element)
    else:
      total_sum += element
  return total_sum

# Example usage:
nested_list = [[1, 2], [3, [4, 5]], 6]
result = sum_nested(nested_list)
print(f"The sum of all elements in {nested_list} is: {result}")

nested_list_2 = [1, [2, [3, 4], 5], 6]
result_2 = sum_nested(nested_list_2)
print(f"The sum of all elements in {nested_list_2} is: {result_2}")

The sum of all elements in [[1, 2], [3, [4, 5]], 6] is: 21
The sum of all elements in [1, [2, [3, 4], 5], 6] is: 21


In [19]:
def find_max(lst):
    maximum = float('-inf')

    for item in lst:
        if isinstance(item, list):
            value = find_max(item)
            maximum = max(maximum, value)
        else:
            maximum = max(maximum, item)

    return maximum

nested_list = [[1, 2], [3, [4, 5]], 6]

result = find_max(nested_list)
print(result)

6


In [20]:
def count_occurrences(lst, elem):
    count = 0

    for item in lst:
        if isinstance(item, list):
            count += count_occurrences(item, elem)
        else:
            if item == elem:
                count += 1

    return count

lst = [[1, 2], [2, 3], [2, 4]]
elem = 2

result = count_occurrences(lst, elem)
print(result)

3


In [21]:
def average_nested(lst):
    total = 0
    count = 0

    for item in lst:
        if isinstance(item, list):
            sub_total, sub_count = average_nested(item)
            total += sub_total
            count += sub_count
        else:
            total += item
            count += 1

    return total, count

def get_average(lst):
    total, count = average_nested(lst)
    return total / count

nested_list = [[1, 2], [3, 4], [5, 6]]

result = get_average(nested_list)
print(result)

3.5


In [22]:
import numpy as np

In [23]:
arr1 = np.empty((2, 2))
print(arr1)

[[3.61485080e-315 0.00000000e+000]
 [4.99006302e-322 2.73418259e-052]]


In [24]:
arr2 = np.ones((4, 2))
print(arr2)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [26]:
arr3 = np.full((3, 4), 7)
print(arr3)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [28]:
arr4 = np.zeros_like(arr3)
print(arr4)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [30]:
arr5 = np.ones_like(arr3)
print(arr5)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [31]:
new_list = [1, 2, 3, 4]

arr6 = np.array(new_list)
print(arr6)

[1 2 3 4]


In [32]:
arr1 = np.arange(10, 50)
print(arr1)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [33]:
arr2 = np.arange(9).reshape(3, 3)
print(arr2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [34]:
arr3 = np.eye(3)
print(arr3)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [35]:
arr4 = np.random.random(30)
mean_value = arr4.mean()

print(arr4)
print("Mean:", mean_value)

[0.87233006 0.53667005 0.13130509 0.94463451 0.24822419 0.1414056
 0.169274   0.48453365 0.93347658 0.00765906 0.51801165 0.89165975
 0.88096547 0.56867609 0.26129599 0.04479549 0.69779128 0.07355987
 0.69988934 0.15338582 0.99292148 0.78685684 0.25075153 0.04980499
 0.77049561 0.61848362 0.05927841 0.39377204 0.08345657 0.87853069]
Mean: 0.47146317670607857


In [36]:
arr5 = np.random.random((10, 10))

print("Minimum:", arr5.min())
print("Maximum:", arr5.max())

Minimum: 0.004261919790937041
Maximum: 0.9850379631195387


In [37]:
arr6 = np.zeros(10)
arr6[4] = 1

print(arr6)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [38]:
arr7 = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr7[::-1]

print(reversed_arr)

[0 4 0 0 2 1]


In [39]:
arr8 = np.ones((5, 5))
arr8[1:-1, 1:-1] = 0

print(arr8)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [40]:
arr9 = np.zeros((8, 8))
arr9[1::2, ::2] = 1
arr9[::2, 1::2] = 1

print(arr9)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [41]:
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11,12])

In [42]:
add_result = x + y
print(add_result)

[[ 6  8]
 [10 13]]


In [43]:
sub_result = x - y
print(sub_result)

[[-4 -4]
 [-4 -3]]


In [44]:
mul_result = x * 3
print(mul_result)

[[ 3  6]
 [ 9 15]]


In [45]:
square_result = x ** 2
print(square_result)

[[ 1  4]
 [ 9 25]]


In [46]:
dot_vw = np.dot(v, w)
print(dot_vw)

219


In [47]:
dot_xv = np.dot(x, v)
print(dot_xv)

[29 77]


In [48]:
dot_xy = np.dot(x, y)
print(dot_xy)

[[19 22]
 [50 58]]


In [49]:
concat_xy = np.concatenate((x, y), axis=0)
print(concat_xy)

[[1 2]
 [3 5]
 [5 6]
 [7 8]]


In [50]:
concat_vw = np.column_stack((v, w))
print(concat_vw)

[[ 9 11]
 [10 12]]


In [51]:
np.concatenate((x, v))

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [52]:
v2 = v.reshape(1,2)

result = np.concatenate((x, v2), axis=0)
print(result)

[[ 1  2]
 [ 3  5]
 [ 9 10]]


In [53]:
A = np.array([[3, 4],
              [7, 8]])

B = np.array([[5, 3],
              [2, 1]])

In [54]:
A_inv = np.linalg.inv(A)

print("A inverse:")
print(A_inv)

print("\nA * A_inv:")
print(np.dot(A, A_inv))

A inverse:
[[-2.    1.  ]
 [ 1.75 -0.75]]

A * A_inv:
[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


In [55]:
AB = np.dot(A, B)
BA = np.dot(B, A)

print("AB =")
print(AB)

print("\nBA =")
print(BA)

AB =
[[23 13]
 [51 29]]

BA =
[[36 44]
 [13 16]]


In [56]:
AB_T = AB.T
BT_AT = np.dot(B.T,A.T)

print("(AB)^T =")
print(AB_T)

print("\nB^T A^T =")
print(BT_AT)

(AB)^T =
[[23 51]
 [13 29]]

B^T A^T =
[[23 51]
 [13 29]]


In [57]:
A_eq = np.array([[2, -3, 1],
                 [1, -1, 2],
                 [3,  1, -1]])

B_eq = np.array([[-1],
                 [-3],
                 [9]])

In [58]:
A_eq_inv = np.linalg.inv(A_eq)
X = np.dot(A_eq_inv, B_eq)

print("Solution X =")
print(X)

Solution X =
[[ 2.]
 [ 1.]
 [-2.]]


In [59]:
X = np.linalg.inv(A_eq).dot(B_eq)

print("Solution using np.linalg.inv():")
print(X)

Solution using np.linalg.inv():
[[ 2.]
 [ 1.]
 [-2.]]


In [60]:
import numpy as np

# Matrix operations
A = np.array([[3, 4],
              [7, 8]])

B = np.array([[5, 3],
              [2, 1]])

# 1. Prove A * A^-1 = I
A_inv = np.linalg.inv(A)
print("A inverse:")
print(A_inv)

print("\nA * A_inv:")
print(np.dot(A, A_inv))

# 2. Prove AB != BA
AB = np.dot(A, B)
BA = np.dot(B, A)

print("\nAB =")
print(AB)

print("\nBA =")
print(BA)

# 3. Prove (AB)^T = B^T A^T
print("\n(AB)^T =")
print(AB.T)

print("\nB^T A^T =")
print(np.dot(B.T, A.T))

# Linear equation solving
A_eq = np.array([[2, -3, 1],
                 [1, -1, 2],
                 [3,  1, -1]])

B_eq = np.array([[-1],
                 [-3],
                 [9]])

# Solve using inverse method
X = np.dot(np.linalg.inv(A_eq), B_eq)

print("\nSolution of the system:")
print(X)

A inverse:
[[-2.    1.  ]
 [ 1.75 -0.75]]

A * A_inv:
[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

AB =
[[23 13]
 [51 29]]

BA =
[[36 44]
 [13 16]]

(AB)^T =
[[23 51]
 [13 29]]

B^T A^T =
[[23 51]
 [13 29]]

Solution of the system:
[[ 2.]
 [ 1.]
 [-2.]]


In [61]:
import time
import numpy as np

# Create two lists of size 1,000,000
list1 = list(range(1000000))
list2 = list(range(1000000))

# Measure time
start = time.time()

result_list = [list1[i] + list2[i] for i in range(len(list1))]

end = time.time()

print("Time taken using Python Lists:", end - start)

Time taken using Python Lists: 0.1157522201538086


In [62]:
import time
import numpy as np

# Create numpy arrays
arr1 = np.arange(1000000)
arr2 = np.arange(1000000)

# Measure time
start = time.time()

result_array = arr1 + arr2

end = time.time()

print("Time taken using NumPy Arrays:", end - start)

Time taken using NumPy Arrays: 0.0038285255432128906


In [63]:
# Create two lists
list1 = list(range(1000000))
list2 = list(range(1000000))

start = time.time()

result_list = [list1[i] * list2[i] for i in range(len(list1))]

end = time.time()

print("Time taken using Python Lists:", end - start)

Time taken using Python Lists: 0.16690564155578613


In [64]:
# Create numpy arrays
arr1 = np.arange(1000000)
arr2 = np.arange(1000000)

start = time.time()

result_array = arr1 * arr2

end = time.time()

print("Time taken using NumPy Arrays:", end - start)

Time taken using NumPy Arrays: 0.004526376724243164


In [65]:
# Create lists
list1 = list(range(1000000))
list2 = list(range(1000000))

start = time.time()

dot_product = 0
for i in range(len(list1)):
    dot_product += list1[i] * list2[i]

end = time.time()

print("Dot Product (Python Lists):", dot_product)
print("Time taken using Python Lists:", end - start)

Dot Product (Python Lists): 333332833333500000
Time taken using Python Lists: 0.4821140766143799


In [66]:
# Create numpy arrays
arr1 = np.arange(1000000)
arr2 = np.arange(1000000)

start = time.time()

dot_product_np = np.dot(arr1, arr2)

end = time.time()

print("Dot Product (NumPy):", dot_product_np)
print("Time taken using NumPy:", end - start)

Dot Product (NumPy): 333332833333500000
Time taken using NumPy: 0.0019519329071044922


In [67]:
# Create two 1000x1000 matrices using Python lists
size = 1000

A = [[1 for _ in range(size)] for _ in range(size)]
B = [[1 for _ in range(size)] for _ in range(size)]

# Result matrix
C = [[0 for _ in range(size)] for _ in range(size)]

start = time.time()

for i in range(size):
    for j in range(size):
        for k in range(size):
            C[i][j] += A[i][k] * B[k][j]

end = time.time()

print("Time taken using Python Lists:", end - start)

Time taken using Python Lists: 311.3258366584778


In [68]:
# Create numpy matrices
A = np.ones((1000, 1000))
B = np.ones((1000, 1000))

start = time.time()

C = np.dot(A, B)

end = time.time()

print("Time taken using NumPy:", end - start)

Time taken using NumPy: 0.08486747741699219
